name: Evaluate Student Answer

on:
  workflow_dispatch:
    inputs:
      question:
        description: 'Question'
        required: true
      reference_answer:
        description: 'Reference Answer'
        required: true
      student_answer:
        description: 'Student Answer'
        required: true

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          # If you have dependencies, install them here
          # pip install -r requirements.txt
      - name: Run Evaluation Script
        run: python evaluate.py
        env:
          QUESTION: ${{ github.event.inputs.question }}
          REFERENCE_ANSWER: ${{ github.event.inputs.reference_answer }}
          STUDENT_ANSWER: ${{ github.event.inputs.student_answer }}
